- name: ensure github.com is a known host
  lineinfile:
    dest: /home/deployer/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    owner: deployer
    group: deployer
