- name: add systemd service definition
  template:
    src: flask.service.j2
    dest: /etc/systemd/system/flask.service
    mode: 0600
  tags: ['flask-config']

- name: load configs
  shell: sudo systemctl daemon-reload

- name: Enable Flask Service
  ansible.builtin.systemd:
    name: flask
    enabled: yes
    state: started
  tags: ['flask-config']

- name: add flask sudoers configuration
  template:
    src: sudo.j2
    dest: /etc/sudoers.d/{{ deploy_user }}
    mode: 0600
