# proctor key (Administering the test)
proctor_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAhLwOu11GmTZ1vOormmaygACw2bCQaj22kwFH05dNtLhJrGgzhiAJxmoKNje9+PFx1d8LHLL2ydycD2Tta+uIDSxzqHkH7yN2guYB0sebvKb3fkdV+SR7/UbwTC7BSLVol2Eu4twhPnhnrNOWcba89HIPytBJHm/JmaLUTfryD+QkxaRIKo/qUS7DwXTE1dGO5r+Hg4DN2fWOJQxkEiiuUrAS9d8RwXvktFgKDKCy7Gw0TcnyWccG4MTPMliY3QELDY0sMhuMIGnx8UGHD547AsxnJ8fEW6K+LzzjQIVRPCymDBIO1T8Ue/NEjrTpj8BANhxZlqq8UBG9bOQf3kGmOIlCOBz4lZQpi3ahKHbmHi5LojhiOlpeKJk+miHgEJ7lzFVesB7On7T2HB/D8BALvN3g2LPJP0oxYIEjvA0dd64+8jbyo59xGLQBvP9dxIAsJjoXdUAhMRBfww9XiIylz5fXCnDt4mvNiq//JqKidsDIeg/Y5Vs45JBa5PFi8Rc= shey@earth"

# candidate key
candidate_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAhLwOu11GmTZ1vOormmaygACw2bCQaj22kwFH05dNtLhJrGgzhiAJxmoKNje9+PFx1d8LHLL2ydycD2Tta+uIDSxzqHkH7yN2guYB0sebvKb3fkdV+SR7/UbwTC7BSLVol2Eu4twhPnhnrNOWcba89HIPytBJHm/JmaLUTfryD+QkxaRIKo/qUS7DwXTE1dGO5r+Hg4DN2fWOJQxkEiiuUrAS9d8RwXvktFgKDKCy7Gw0TcnyWccG4MTPMliY3QELDY0sMhuMIGnx8UGHD547AsxnJ8fEW6K+LzzjQIVRPCymDBIO1T8Ue/NEjrTpj8BANhxZlqq8UBG9bOQf3kGmOIlCOBz4lZQpi3ahKHbmHi5LojhiOlpeKJk+miHgEJ7lzFVesB7On7T2HB/D8BALvN3g2LPJP0oxYIEjvA0dd64+8jbyo59xGLQBvP9dxIAsJjoXdUAhMRBfww9XiIylz5fXCnDt4mvNiq//JqKidsDIeg/Y5Vs45JBa5PFi8Rc= shey@earth"

## less likely to change
redis_socket_path: "/var/run/redis/redis-server.sock"
deploy_user: deployer

# flask app
flask_app_name: "sre-candidate-app"
flask_git_repo: "git@github.com:shey/{{ flask_app_name }}.git"
flask_app_home: "/home/{{ deploy_user }}/{{ flask_app_name }}"
flask_branch: main

# user keys:
users:
  deployer:
    ssh_key:
      - "{{ proctor_key }}"
      - "{{ candidate_key }}"

  ubuntu:
    ssh_key:
      - "{{ proctor_key }}"
      - "{{ candidate_key }}"
