- name: generate password for user
  shell: makepasswd --chars=128
  register: user_password
  no_log: True

- name: create a user
  user:
    name: "{{ username }}"
    createhome: yes
    shell: /bin/bash
    password: "{{ user_password.stdout | password_hash('sha512') }}"
    state: present

- name: create ssh directory for {{ username }}
  become_user: "{{ username }}"
  file:
    path: ~/.ssh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
    state: directory

- name: add ssh keys {{ username }}
  template:
    src: authorized_keys.j2
    dest: /home/{{ username }}/.ssh/authorized_keys
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
