- name: Install NTP
  apt:
    name: ntp
    state: latest

- name: Enable NTP
  service:
    name: ntp
    state: started
    enabled: yes

- name: Set timezone variables
  copy:
    content: 'Etc/UTC'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
